"""empty message

Revision ID: 4d11aaab1f8e
Revises: d586283f1aa9
Create Date: 2020-11-22 23:58:36.180255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d11aaab1f8e'
down_revision = 'd586283f1aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('show_id', sa.Integer(), nullable=False))
    op.drop_column('Show', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('Show', 'show_id')
    # ### end Alembic commands ###
