"""empty message

Revision ID: 6131a19ec1e9
Revises: ed8b788fd93d
Create Date: 2020-11-22 14:16:31.258168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6131a19ec1e9'
down_revision = 'ed8b788fd93d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue_genre', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('venue_genre_venue_id_fkey', 'venue_genre', type_='foreignkey')
    op.drop_constraint('venue_genre_genre_id_fkey', 'venue_genre', type_='foreignkey')
    op.create_foreign_key(None, 'venue_genre', 'Artist', ['id'], ['id'])
    op.drop_column('venue_genre', 'genre_id')
    op.drop_column('venue_genre', 'venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue_genre', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('venue_genre', sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'venue_genre', type_='foreignkey')
    op.create_foreign_key('venue_genre_genre_id_fkey', 'venue_genre', 'Artist', ['genre_id'], ['id'])
    op.create_foreign_key('venue_genre_venue_id_fkey', 'venue_genre', 'Venue', ['venue_id'], ['id'])
    op.drop_column('venue_genre', 'id')
    # ### end Alembic commands ###
