"""empty message

Revision ID: 795d7d8140a7
Revises: 88b792842734
Create Date: 2020-11-22 14:29:13.810128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795d7d8140a7'
down_revision = '88b792842734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue_genre', sa.Column('genre_id', sa.Integer(), nullable=False))
    op.add_column('venue_genre', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.drop_constraint('venue_genre_id_fkey', 'venue_genre', type_='foreignkey')
    op.create_foreign_key(None, 'venue_genre', 'Genre', ['genre_id'], ['id'])
    op.create_foreign_key(None, 'venue_genre', 'Venue', ['venue_id'], ['id'])
    op.drop_column('venue_genre', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue_genre', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'venue_genre', type_='foreignkey')
    op.drop_constraint(None, 'venue_genre', type_='foreignkey')
    op.create_foreign_key('venue_genre_id_fkey', 'venue_genre', 'Genre', ['id'], ['id'])
    op.drop_column('venue_genre', 'venue_id')
    op.drop_column('venue_genre', 'genre_id')
    # ### end Alembic commands ###
