"""empty message

Revision ID: 88b792842734
Revises: 6131a19ec1e9
Create Date: 2020-11-22 14:21:38.302653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b792842734'
down_revision = '6131a19ec1e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('venue_genre_id_fkey', 'venue_genre', type_='foreignkey')
    op.create_foreign_key(None, 'venue_genre', 'Genre', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue_genre', type_='foreignkey')
    op.create_foreign_key('venue_genre_id_fkey', 'venue_genre', 'Artist', ['id'], ['id'])
    # ### end Alembic commands ###
