"""empty message

Revision ID: 9bc3e3445e50
Revises: dab5c6c39a11
Create Date: 2020-11-23 11:27:00.185785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc3e3445e50'
down_revision = 'dab5c6c39a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('show_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'show_name')
    # ### end Alembic commands ###
